import "./css/skills.css";
import Aos from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
export const Skills = () => {
  useEffect(() => {
    Aos.init();
  }, []);
  return (
    <div
      id="skills"
      className="bloque-skills"
    >
      <div
        data-aos="fade-right"
        data-aos-duration="2000"
        className="bloque-titulos"
      >
        <h1 className="fondo-titulo">Skills</h1>
        <h2 className="titulo">Skills</h2>
      </div>
      <section className="container section-skills">
        <article
          data-aos="fade-up"
          data-aos-duration="500"
          className="skill-item"
        >
          <img
            src="./assets/java_original.png"
            alt="java"
          />
          <p>Java</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="700"
          className="skill-item"
        >
          <img
            src={"/assets/mysql.png"}
            alt="java"
          />
          <p>MySql</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="1000"
          className="skill-item"
        >
          <img
            src={"assets/spring.png"}
            alt="java"
          />
          <p>Spring</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="1200"
          className="skill-item"
        >
          <img
            src={"./assets/html.png"}
            alt="java"
          />
          <p>HTML</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="1400"
          className="skill-item"
        >
          <img
            src="./assets/css.png"
            alt="java"
          />
          <p>CSS</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="1600"
          className="skill-item"
        >
          <img
            src="./assets/javascript.png"
            alt="java"
          />
          <p>Javascript</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="1800"
          className="skill-item"
        >
          <img
            src="./assets/react.png"
            alt="java"
          />
          <p>React Js</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="2000"
          className="skill-item"
        >
          <img
            src="./assets/figma.png"
            alt="java"
          />
          <p>Figma</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="2200"
          className="skill-item"
        >
          <img
            src="./assets/github.png"
            alt="java"
          />
          <p>GitHub</p>
        </article>
        <article
          data-aos="fade-up"
          data-aos-duration="2400"
          className="skill-item"
        >
          <img
            src="./assets/bootstrap.png"
            alt="java"
          />
          <p>Bootstrap</p>
        </article>
      </section>
    </div>
  );
};
